### ISSUE TITLE
Constant 404 Not Found errors when creating secrets and AddType System.Web requirement?

### ISSUE THREAD

**Issue by UoCKen** [chelnak/OneTimeSecret#13]
Steps to reproduce
------------------
I have no issue getting an authorization token. I do that first:
PS V:\Scripts> Set-OTSAuthorizationToken -Username xxxx@yyyy.com -APIKey xxxxxxxxxxxxxxx -BaseUrl https://onetimesecret.com

Authorization                                                                                            BaseUrl
-------------                                                                                            -------
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz https://onetimesecret.com/

First, why do I have to add the type, System.Web? Shouldn't the module handle this?
PS V:\Scripts> New-OTSSharedSecret -Secret "This is a test secret." -Verbose
VERBOSE: Adding Secret Query Parameter
VERBOSE: Performing the operation "New-OTSSharedSecret" on target "onetimesecret.com".
Unable to find type [System.Web.HttpUtility].
At C:\Program Files\WindowsPowerShell\Modules\onetimesecret\2.2.1\OneTimeSecret.psm1:140 char:24
+         $QueryString = [System.Web.HttpUtility]::ParseQueryString([st ...
+                        ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Web.HttpUtility:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

PS V:\Scripts> Add-Type -AssemblyName System.Web

Now onto the 404 errors:
PS V:\Scripts> New-OTSSharedSecret -Secret "This is a test secret." -Verbose
VERBOSE: Adding Secret Query Parameter
VERBOSE: Performing the operation "New-OTSSharedSecret" on target "onetimesecret.com".
VERBOSE: Invoking request with headers System.Collections.Hashtable
VERBOSE: POST https://onetimesecret.com/api/v1/share?secret=This+is+a+test+secret. with 0-byte payload
Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\onetimesecret\2.2.1\OneTimeSecret.psm1:166 char:25
+ ... $Response = Invoke-RestMethod -Method $Method -Headers $Headers -Uri  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Expected behavior
-----------------
I expect a return of the secret key data.

Actual behavior
---------------
404 errors as shown above.

Environment data
----------------

```powershell
> $PSVersionTable
PS V:\Scripts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.4046
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4046
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Get-Module -Name OneTimeSecret | Format-List
PS V:\Scripts> Get-Module -Name OneTimeSecret | Format-List

Name              : onetimesecret
Path              : C:\Program Files\WindowsPowerShell\Modules\onetimesecret\2.2.1\OneTimeSecret.psm1
Description       : PowerShell Module for OneTimeSecret.com
ModuleType        : Script
Version           : 2.2.1
NestedModules     : {}
ExportedFunctions : {Get-OTSAuthorizationToken, Get-OTSRecentMetadata, Get-OTSSecret, Get-OTSSecretMetadata...}
ExportedCmdlets   :
ExportedVariables :
ExportedAliases   :
```

**Comment by paulmellors40** [comment]
I don't get the 
`Unable to find type [System.Web.HttpUtility].`
but do get the same 404 issue if I add the param -Recipient

**Comment by UoCKen** [comment]
Found the API issue. It is due to a hidden char that snuck into my username, rendering the API key invalid -- but there is no error code for this, just 404 errors. However, even fixing this, I still get the error, "Unable to find type [System.Web.HttpUtility]" which I can deal with easily enough I suppose. Closing.
