### ISSUE TITLE
Allow to set base URL pointing to a private OTS instance

### ISSUE THREAD

**Issue by armando82** [chelnak/OneTimeSecret#8]
Any chances of allowing to set the base URL to a private instance of OTS?

They are OK with this as per the last line of their About Us:
https://onetimesecret.com/about

This could be done on the Set-OTSConnectionInformation cmdlet or a brand new cmdlet in the module. I could just fork the repo, but I find it cleaner if the original module is more complete.

**Comment by chooko** [comment]
I would second this.

At the moment, OTS is under maintenance, and looks like it will be for the unforeseeable future.

I rely on your PowerShell module in a couple different script that require the sharing of secrets. I'd love to stand up my own instance or use https://cloak.sh to continue sending secrets.

**Comment by chelnak** [comment]
OK I’ll look to get this implemented this week providing I can get the time.

Feel free to push a PR in the meantime though if you’ve got something in
mind.

**Comment by chelnak** [comment]
@armando82 @chooko 

Have pushed #9 to address the issue. It would be great if you could verify that the new feature works for your setups. Can you test?

You'll need to clone and checkout **custom_url**. I'd also recommend building and importing the module from the release folder.

```
.\tools\build.ps1
Import-Module .\Release\OneTimeSecret\ -Force
```

If everything is OK i'll push 2.2.0 to the gallery tomorrow.

**Comment by chelnak** [comment]
Custom Urls are now supported as of 2.2.0
